-- Stef guestbook: Supabase setup
-- Run this once in the Supabase SQL Editor.

create table if not exists public.memories (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 100),
  connection text not null check (char_length(trim(connection)) between 1 and 120),
  location text check (location is null or char_length(location) <= 150),
  memory text not null check (char_length(trim(memory)) between 1 and 5000),
  photo_url text check (photo_url is null or char_length(photo_url) <= 2000),
  permission boolean not null default false check (permission = true),
  published boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.memories enable row level security;

drop policy if exists "Anyone can read published memories" on public.memories;
create policy "Anyone can read published memories"
on public.memories for select to anon, authenticated
using (published = true);

drop policy if exists "Anyone can submit a memory" on public.memories;
create policy "Anyone can submit a memory"
on public.memories for insert to anon, authenticated
with check (permission = true and published = true);

-- Admin access: authenticated users can manage memories.
-- Create your admin user in Supabase Authentication and disable public sign-ups.
drop policy if exists "Authenticated users can manage memories" on public.memories;
create policy "Authenticated users can manage memories"
on public.memories for select to authenticated
using (true);

drop policy if exists "Authenticated users can update memories" on public.memories;
create policy "Authenticated users can update memories"
on public.memories for update to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated users can delete memories" on public.memories;
create policy "Authenticated users can delete memories"
on public.memories for delete to authenticated
using (true);

create index if not exists memories_published_created_idx
on public.memories (published, created_at desc);
